# Generated by Django 2.0.1 on 2018-01-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=300)),
                ('league', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=4)),
                ('numberofteams', models.IntegerField(default=0)),
                ('numberofgames', models.IntegerField(default=0)),
                ('sourcelastupdated', models.CharField(max_length=15)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('caption',),
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(default=0)),
                ('fixturedate', models.DateTimeField()),
                ('matchday', models.IntegerField(default=0)),
                ('hometeamid', models.IntegerField(default=0)),
                ('hometeamname', models.CharField(max_length=300)),
                ('awayteamid', models.IntegerField(default=0)),
                ('awayteamname', models.CharField(max_length=300)),
                ('goalshometeam', models.IntegerField(default=0)),
                ('goalsawayteam', models.IntegerField(default=0)),
                ('sourcelastupdated', models.CharField(max_length=15)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Competition')),
            ],
            options={
                'ordering': ('matchday',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('isadmin', models.BooleanField()),
                ('communities', models.ManyToManyField(to='community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('shortname', models.CharField(max_length=5)),
                ('sqaudmarketvalue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
