# Generated by Django 2.0.5 on 2018-05-26 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=300)),
                ('league', models.CharField(max_length=5)),
                ('year', models.IntegerField(default=0)),
                ('currentMatchday', models.IntegerField(default=0)),
                ('numberOfMatchdays', models.IntegerField(default=0)),
                ('numberOfTeams', models.IntegerField(default=0)),
                ('numberOfGames', models.IntegerField(default=0)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('caption', 'lastUpdated'),
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
                ('matchday', models.IntegerField(default=0)),
                ('homeTeamName', models.CharField(max_length=300)),
                ('homeTeamId', models.IntegerField(default=0)),
                ('awayTeamName', models.CharField(max_length=300)),
                ('awayTeamId', models.IntegerField(default=0)),
                ('goalsHomeTeam', models.IntegerField(default=0)),
                ('goalsAwayTeam', models.IntegerField(default=0)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Competition')),
            ],
            options={
                'ordering': ('matchday',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('ispublic', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('fixtures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Fixture')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Group')),
            ],
            options={
                'ordering': ('createddate',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('isadmin', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Group')),
            ],
            options={
                'ordering': ('date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awayteamgoals', models.IntegerField(default=0)),
                ('hometeamgoals', models.IntegerField(default=0)),
                ('iscorrect', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('fixtures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Fixture')),
                ('memberships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Membership')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('shortname', models.CharField(max_length=5)),
                ('sqaudmarketvalue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='games',
            field=models.ManyToManyField(through='community.GroupFixture', to='community.Fixture'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='community.Membership', to='community.Profile'),
        ),
    ]
